### ISSUE TITLE
Wrong cursor colour when using  PaymentCard

### ISSUE THREAD

**Issue by jszmltr** [evervault/evervault-android#50]
When using [com.evervault.sdk.input.ui.card.PaymentCard](https://github.com/evervault/evervault-android/blob/main/evervault-inputs/src/main/java/com/evervault/sdk/input/ui/card/PaymentCard.kt) the colour of the cursor is incorrect. It's always Black even in the DarkMode. 

You can see this in the sample app: 
![Screenshot_20240116_213337](https://github.com/evervault/evervault-android/assets/6136159/709c0bb6-cbbf-46ba-8a90-6d7f505fac06)

**Comment by boilsquid** [comment]
Fixed in v1.10.0.
