### ISSUE TITLE
Encryption not working on release builds

### ISSUE THREAD

**Issue by 7alma9z** [evervault/evervault-android#59]
I am facing a critical issue on Android, I am using evervault sdk to encrypt the private key but in the release build encryption is throwing error
“no such algorithm: ECDH for provider BC”

**Comment by lfarrel6** [comment]
This was found to be as a result of the proguard rules config of the project. The required proguard rules for the Evervault SDK are documented [here](https://docs.evervault.com/sdks/android#proguard-rules).
